#!/bin/bash

ARQUIVO_JSON="$1"

if [ -z "$ARQUIVO_JSON" ]; then
    echo -e "\nUso: $0 <arquivo_json>\n"
    exit 1
fi

if [ ! -f "$ARQUIVO_JSON" ]; then
    echo -e "\nArquivo JSON não encontrado: $ARQUIVO_JSON\n"
    exit 1
fi

PROTOCOLO=$(jq -r '.start.test_start.protocol' "$ARQUIVO_JSON")

if "$(jq '.start | has("accepted_connection")' $ARQUIVO_JSON)"; then
    # Se for o servidor
    if [ "$PROTOCOLO" = "UDP" ]; then
        echo "total_bytes_transferidos,taxa_de_bits_por_segundo,jitter,total_pacotes_perdidos,porcentagem_pacotes_perdidos"
        jq -r '.intervals[].sum as $soma | .start.connected[0] as $conexao | "\($conexao.remote_host),\($conexao.remote_port),\($soma.bytes),\($soma.bits_per_second),\($soma.jitter_ms),\($soma.lost_packets),\($soma.lost_percent)"' "$ARQUIVO_JSON"

    else
        echo "total_bytes_transferidos,taxa_de_bits_por_segundo,jitter,total_pacotes_perdidos,porcentagem_pacotes_perdidos"
        jq -r '.intervals[].sum as $soma | "\($soma.bytes),\($soma.bits_per_second),0,0,0"' "$ARQUIVO_JSON"
    fi

else
    # Se for o cliente
    if [ "$PROTOCOLO" = "UDP" ]; then
        echo "host_destino,porta_destino,protocolo,bytes_transferidos,bits_por_segundo"
        jq -r '.intervals[].sum as $soma | .start.connected[0] as $conexao | "\($conexao.remote_host),\($conexao.remote_port),\(.start.test_start.protocol),\($soma.bytes),\($soma.bits_per_second)"' "$ARQUIVO_JSON"

    else
        echo "host_destino,porta_destino,protocolo,pacotes_perdidos,%_pacotes_perdidos,bytes_transferidos,bits_por_segundo"
        jq -r '.intervals[].sum as $soma | .start.connected[0] as $conexao | "\($conexao.remote_host),\($conexao.remote_port),\(.start.test_start.protocol)_\(.end.sender_tcp_congestion)_\(.end.receiver_tcp_congestion),\($soma.retransmits),0,\($soma.bytes),\($soma.bits_per_second)"' "$ARQUIVO_JSON"
    fi
fi